default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: torah_app_development

test:
  <<: *default
  host: localhost
  database: torah_app_test

production:
  <<: *default
  database: torah_app_production
  username: torah_app
  password: <%= ENV['TORAH_APP_DATABASE_PASSWORD'] %>
